import time
from selenium.common.exceptions import TimeoutException, NoSuchElementException, ElementClickInterceptedException, ElementNotInteractableException

from pages.login_page import LoginPage
from pages.main_page import MainPage
from pages.lesson_page import LessonPage
from pages.homework_page import HomeworkPage
from pages.coworking_page import CoworkingPage

# Browser_Chrome
def test_my_proweb_chrome(driver_chrome):
    driver_chrome.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_chrome)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("998970072930")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)
    login_page.enter_input_password("Dmitriy12345")
    time.sleep(3)
    login_page.click_btn_login()
    time.sleep(3)
    try:
        login_page.click_device_1()
        time.sleep(3)
        login_page.click_finish_1()
        time.sleep(3)
    except (TimeoutException, NoSuchElementException):
        pass


    lesson_page = LessonPage(driver_chrome)
    lesson_page.click_home()
    time.sleep(3)
    lesson_page.click_my_groups()
    time.sleep(3)
    lesson_page.click_lessons()
    time.sleep(3)
    lesson_page.click_lesson_video()
    time.sleep(3)
    lesson_page.click_fullscreen()
    time.sleep(3)
    lesson_page.click_play()
    time.sleep(3)
    lesson_page.watch_video_100_seconds()
    lesson_page.click_exit_fullscreen()
    time.sleep(3)
    lesson_page.rate_lesson()
    time.sleep(3)

    homework_page = HomeworkPage(driver_chrome)
    lesson_page.click_home()
    time.sleep(3)
    homework_page.click_homework()
    time.sleep(3)
    homework_page.click_lesson()
    time.sleep(3)
    homework_page.click_comments()
    time.sleep(3)
    homework_page.enter_input_comment("test")
    time.sleep(3)
    homework_page.send_comment()
    time.sleep(3)

    coworking_page = CoworkingPage(driver_chrome)
    lesson_page.click_home()
    time.sleep(3)
    coworking_page.click_coworking()
    time.sleep(3)
    coworking_page.click_book()
    time.sleep(3)
    coworking_page.check_rules_and_next()
    time.sleep(3)
    time.sleep(3)
    coworking_page.select_oybek()
    time.sleep(3)
    coworking_page.click_select_branch()
    time.sleep(3)
    coworking_page.select_date()
    time.sleep(3)
    coworking_page.select_group()
    time.sleep(3)
    coworking_page.select_group_circle()
    time.sleep(3)
    coworking_page.click_select_group()
    time.sleep(3)
    coworking_page.select_time()
    time.sleep(3)
    coworking_page.select_time_cell(15)
    time.sleep(3)
    coworking_page.click_select_time()
    time.sleep(3)
    coworking_page.select_place()
    time.sleep(3)
    coworking_page.select_place_cell()
    time.sleep(3)
    coworking_page.click_confirm_place()
    time.sleep(3)
    coworking_page.click_final_book()
    time.sleep(3)


    main_page = MainPage(driver_chrome)
    main_page.click_profile_icon()
    time.sleep(3)
    main_page.click_logout_btn()
    time.sleep(3)
    main_page.click_exit_confirm()
    time.sleep(3)

# Test_Invalid_Chrome
# Invalid_Login
def test_my_proweb_chrome(driver_chrome):
     driver_chrome.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
     login_page = LoginPage(driver_chrome)
     login_page.change_lang_ru()
     time.sleep(3)
     login_page.enter_input_login("111111111111")
     time.sleep(3)
     login_page.click_btn_enter()
     time.sleep(3)


# Test_Invalid_Chrome
# Invalid_Password
def test_my_proweb_chrome(driver_chrome):
     driver_chrome.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
     login_page = LoginPage(driver_chrome)
     login_page.change_lang_ru()
     time.sleep(3)
     login_page.enter_input_login("998970072930")
     time.sleep(3)
     login_page.click_btn_enter()
     time.sleep(3)
     login_page.enter_input_password("Dmitriу12345")
     time.sleep(3)
     login_page.click_btn_login()
     time.sleep(3)


# Browser_Edge
def test_my_proweb_edge(driver_edge):
    driver_edge.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_edge)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("998970072930")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)
    login_page.enter_input_password("Dmitriy12345")
    time.sleep(3)
    login_page.click_btn_login()
    time.sleep(3)
    try:
        login_page.click_device_1()
        time.sleep(3)
        login_page.click_finish_1()
        time.sleep(3)
    except (TimeoutException, NoSuchElementException):
        pass

    lesson_page = LessonPage(driver_edge)
    lesson_page.click_home()
    time.sleep(3)
    lesson_page.click_my_groups()
    time.sleep(3)
    lesson_page.click_lessons()
    time.sleep(3)
    lesson_page.click_lesson_video()
    time.sleep(3)
    lesson_page.click_fullscreen()
    time.sleep(3)
    lesson_page.click_play()
    time.sleep(3)
    lesson_page.watch_video_100_seconds()
    lesson_page.click_exit_fullscreen()
    time.sleep(3)
    lesson_page.rate_lesson()
    time.sleep(3)

    homework_page = HomeworkPage(driver_edge)
    lesson_page.click_home()
    time.sleep(3)
    homework_page.click_homework()
    time.sleep(3)
    homework_page.click_lesson()
    time.sleep(3)
    homework_page.click_comments()
    time.sleep(3)
    homework_page.enter_input_comment("test")
    time.sleep(3)
    homework_page.send_comment()
    time.sleep(3)

    coworking_page = CoworkingPage(driver_edge)
    lesson_page.click_home()
    time.sleep(3)
    coworking_page.click_coworking()
    time.sleep(3)
    coworking_page.click_book()
    time.sleep(3)
    coworking_page.check_rules_and_next()
    time.sleep(3)
    time.sleep(3)
    coworking_page.select_oybek()
    time.sleep(3)
    coworking_page.click_select_branch()
    time.sleep(3)
    coworking_page.select_date()
    time.sleep(3)
    coworking_page.select_group()
    time.sleep(3)
    coworking_page.select_group_circle()
    time.sleep(3)
    coworking_page.click_select_group()
    time.sleep(3)
    coworking_page.select_time()
    time.sleep(3)
    coworking_page.select_time_cell(15)
    time.sleep(3)
    coworking_page.click_select_time()
    time.sleep(3)
    coworking_page.select_place()
    time.sleep(3)
    coworking_page.select_place_cell()
    time.sleep(3)
    coworking_page.click_confirm_place()
    time.sleep(3)
    coworking_page.click_final_book()
    time.sleep(3)

    main_page = MainPage(driver_edge)
    main_page.click_profile_icon()
    time.sleep(3)
    main_page.click_logout_btn()
    time.sleep(3)
    main_page.click_exit_confirm()
    time.sleep(3)

# Test_Invalid_Edge
# Invalid_Login
def test_my_proweb_edge(driver_edge):
    driver_edge.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_edge)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("111111111111")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)


# Test_Invalid_Edge
# Invalid_Password
def test_my_proweb_edge(driver_edge):
    driver_edge.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_edge)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("998970072930")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)
    login_page.enter_input_password("Dmitriу12345")
    time.sleep(3)
    login_page.click_btn_login()
    time.sleep(3)


# Browser_Firefox
def test_my_proweb_firefox(driver_firefox):
    driver_firefox.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_firefox)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("998970072930")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)
    login_page.enter_input_password("Dmitriy12345")
    time.sleep(3)
    login_page.click_btn_login()
    time.sleep(3)
    try:
        login_page.click_device_1()
        time.sleep(3)
        login_page.click_finish_1()
        time.sleep(3)
    except (TimeoutException, NoSuchElementException):
        pass

    lesson_page = LessonPage(driver_firefox)
    lesson_page.click_home()
    time.sleep(3)
    lesson_page.click_my_groups()
    time.sleep(3)
    lesson_page.click_lessons()
    time.sleep(3)
    lesson_page.click_lesson_video()
    time.sleep(3)
    lesson_page.click_fullscreen()
    time.sleep(3)
    lesson_page.click_play()
    time.sleep(3)
    lesson_page.watch_video_100_seconds()
    lesson_page.click_exit_fullscreen()
    time.sleep(3)
    lesson_page.rate_lesson()
    time.sleep(3)

    homework_page = HomeworkPage(driver_firefox)
    lesson_page.click_home()
    time.sleep(3)
    homework_page.click_homework()
    time.sleep(3)
    homework_page.click_lesson()
    time.sleep(3)
    homework_page.click_comments()
    time.sleep(3)
    homework_page.enter_input_comment("test")
    time.sleep(3)
    homework_page.send_comment()
    time.sleep(3)

    coworking_page = CoworkingPage(driver_firefox)
    lesson_page.click_home()
    time.sleep(3)
    coworking_page.click_coworking()
    time.sleep(3)
    coworking_page.click_book()
    time.sleep(3)
    coworking_page.check_rules_and_next()
    time.sleep(3)
    time.sleep(3)
    coworking_page.select_oybek()
    time.sleep(3)
    coworking_page.click_select_branch()
    time.sleep(3)
    coworking_page.select_date()
    time.sleep(3)
    coworking_page.select_group()
    time.sleep(3)
    coworking_page.select_group_circle()
    time.sleep(3)
    coworking_page.click_select_group()
    time.sleep(3)
    coworking_page.select_time()
    time.sleep(3)
    coworking_page.select_time_cell(15)
    time.sleep(3)
    coworking_page.click_select_time()
    time.sleep(3)
    coworking_page.select_place()
    time.sleep(3)
    coworking_page.select_place_cell()
    time.sleep(3)
    coworking_page.click_confirm_place()
    time.sleep(3)
    coworking_page.click_final_book()
    time.sleep(3)

    main_page = MainPage(driver_firefox)
    main_page.click_profile_icon()
    time.sleep(3)
    main_page.click_logout_btn()
    time.sleep(3)
    main_page.click_exit_confirm()
    time.sleep(3)

# Test_Invalid_Firefox
# Invalid_Login
def test_my_proweb_firefox(driver_firefox):
    driver_firefox.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_firefox)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("111111111111")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)

# Test_Invalid_Firefox
# Invalid_Password
def test_my_proweb_firefox(driver_firefox):
    driver_firefox.get("https://my.proweb.uz/log-in?q=/poll/5/relation/18160")
    login_page = LoginPage(driver_firefox)
    login_page.change_lang_ru()
    time.sleep(3)
    login_page.enter_input_login("998970072930")
    time.sleep(3)
    login_page.click_btn_enter()
    time.sleep(3)
    login_page.enter_input_password("Dmitriу12345")
    time.sleep(3)
    login_page.click_btn_login()
    time.sleep(3)


